### ISSUE TITLE
Figure out integration between CSV Import and other modules

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/CSVImport#1]
The basic prototype for a module that would integrate with this would be Mapping.

**Comment by patrickmj** [comment]
As a big-picture design question, I see two alternatives. One is to let modules add more columns to the existing mapping form (see pic below). Or, it could be set up to let modules add their own entirely new fieldset, passing along the headers from the CSV file to let them set up whatever additional fieldsets they want. 

I lean a bit toward modules tacking on additional fieldsets built on a similar pattern of putting CSV headers in a table, then letting the modules do whatever they want. That'd avoid over-crowding problems with the existing table, and allow more flexibility with how the other modules handle their own data. That would come at the expense of a longer form, but hopefully the collapsing feature would mitigate that. 

Thoughts, @zerocrates @kimisgold and especially @jimsafley since this is thinking about the interaction with Mapping

![csvimportsection](https://cloud.githubusercontent.com/assets/153262/13997825/46de9314-f10a-11e5-9105-33ab3cb38688.png)

**Comment by jimsafley** [comment]
I like the fieldset solution for the reasons you mention.

**Comment by zerocrates** [comment]
The issue there, I think, is that what modules are most likely to want to do is map columns, and that being the case, replicating out that list of columns for each one that wants to do that seems like a pretty poor option.

**Comment by patrickmj** [comment]
Based on convo with @zerocrates the integration options are fluid at this point. More sidebars for modules to add seem in the offing. (see screenshot below)

Another question is where, exactly, other modules can/should tap in. Should  CSVImport pass along each row (and other data) during its own import Job, or should modules tapping in create their own Jobs?

I suspect one 'master' job would be more efficient, but that calls for making sure all the needed data gets passed around at the right places. Adding to the JSON for an item coming from the row might be easy enough, but not sure what other needs a module might have. Any ideas, @jimsafley ?

![modulescsv](https://cloud.githubusercontent.com/assets/153262/14091906/ea64317e-f510-11e5-8214-668edca94bb1.png)
