### ISSUE TITLE
Consider relocating the "user list"

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#115]
Ref #106 
One of the options on the import page is to "automap with user list", with an editable list of lots of options for mapping. 

I don't think it makes sense to have this on the import page. For one, you'd want to have this list for reference before importing. Secondly, the list is the kind of thing which makes more sense in a configuration setting. 

Move it to a module configuration page? Or even a setting in the files, so that it's something only sysadmins can modify?

**Comment by kimisgold** [comment]
The "automap with user list" field is also a pretty unfriendly interface. The default list is long and unwieldy while also leaving plenty of room for typos. It feels like it needs a more fleshed-out interface that goes beyond a textarea. 

I agree with @mebrett that its placement on the import page feels off. It looks like excessive complexity to have on by default, and I'm unclear as to how having both "Automap with labels alone" and "Automap with user list" interact with each other.

**Comment by zerocrates** [comment]
The user list is probably the thing that jumps out at me the most about the interface that I think is problematic. I also don't know quite how it works... I see that it's pre-filled from the configuration and can be changed... does the change there get saved for the user, so it's there by default for future imports?

I almost want to say it makes more sense to have "save/apply mapping" buttons on the "real" mapping interface so you can just apply a previous mapping in its entirety but we don't have this issue of having a different interface for the same thing in two places.

**Comment by patrickmj** [comment]
It also appears to hardcode things specific to other modules (tags, groups). An event that allows other modules to add to the list might be in order to maintain that. Or, we could just force people to add those in themselves.

**Comment by zerocrates** [comment]
I still maintain just saving/restoring of a user's selected mappings is the way to go rather than the list, or even really depending on automapping to any major degree.

As you say, people have their sheets they have and usually don't want to alter them to fit our expectations... whether that's just their own naming scheme or something more fundamental like a different language. That's what the column mapping UI is for, though.

Just letting a user go through the mapping process once and save their resulting mappings feels like the right way to deal with the issue of avoiding repetition, without imposing some "correct" set of column names or building in some sense a totally parallel mapping interface.

Unless I'm mistaken, the ui-improvements branch removed the user list feature completely, not just its UI. So it's not really a case of having a hidden heuristic, but just removing the magic completely.
