### ISSUE TITLE
need clarification on resources import

### ISSUE THREAD

**Issue by alyssafahringer** [omeka-s-modules/CSVImport#117]
Ref #106 - I am unsure of what importing a resources CSV entails--as in, what sort of data would I put into a CSV in order to import a resource.

**Comment by kimisgold** [comment]
@alyssafahringer 'Resources' are a group of Omeka objects that can be described my metadata, so primarily items, item sets, and media. I assume the option to import "Resources" alerts the importer that you're importing multiple types of resources, in contrast to the other single resource options. [Looking at the example spreadsheet file](https://github.com/Daniel-KM/Omeka-S-module-CSVImport/blob/master/test/CsvImportTest/_files/test_resources_heritage.ods), the types are identified in their own "Resource" column.

**Comment by kimisgold** [comment]
Thinking about this, it might be helpful to have that option be more descriptive, like "Multiple resources (items, item sets, media)".

**Comment by mebrett** [comment]
Agreed on having a more descriptive title. 

What are the use cases for people importing multiple resource types in one sheet? (to import media, the item must already exist)

**Comment by Daniel-KM** [comment]
Fixed in https://github.com/omeka-s-modules/CSVImport/pull/105/commits/de68cb1d9879ea987c669ddef4158a38f4d3c5db.

See https://github.com/omeka-s-modules/CSVImport/issues/128 for an explanation of what you can do with import type of resources. This is very useful when the items are logically separated from the media and when there are multiple media for one item. This is allowed in Omeka and it is an important feature.

**Comment by zerocrates** [comment]
Yeah, I think everyone's now clear on what this is intended to enable.
