### ISSUE TITLE
Column delimiter language

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/CSVImport#141]
At present the options are "double quote," "quote," and "hash".  These terms are reasonable, but I wondered if we wanted to make it clearer by calling them "double quote" "single quote" and "hash"

Some of the question here (for me) is what strings Transifex uses that will be readily translated for the right keystroke. But there's also the issue of user legibility.

**Comment by zerocrates** [comment]
We could try to include the actual characters alongside the names, but it's hard to get them to show up with any kind of legibility, especially since we don't really have control over how they look in the dropdown. Translation is definitely something to keep in mind, and there's already issues in English, like "hash" vs. "pound sign" (clearly we should go with "octothorpe").

I don't think there'll be a problem with "single quote," though. Maybe I'll look to see how LibreOffice and other things that work with CSV present that option.

**Comment by zerocrates** [comment]
Libreoffice, at least my version, just has `"` and `'` as the delimiter options in a dropdown. I don't know if we can get away with that, but it would obviate the translation issue

**Comment by mebrett** [comment]
I'm a little concerned about just using the characters in terms of accessibility.
