### ISSUE TITLE
Date import problem from .ODS

### ISSUE THREAD

**Issue by MickaelAHP** [omeka-s-modules/CSVImport#179]
I have noticed a problem importing data (new items) from a .ods file containing text and date.
Text is imported from .ods but not dates whenever cells format is dates. I don't have errors from import log.
From this very same ODS, i create a .csv file, and then dates are imported correctly.
[test.zip](https://github.com/omeka-s-modules/CSVImport/files/4475042/test.zip)

**Comment by zerocrates** [comment]
There's some options with the library we use to read .ods files about how they treat dates within the sheet, so this may just be a case where we need to change something simple like that.

**Comment by pprw** [comment]
It is probably that.

The case below shows a common practice: date were entered in different formats within the sheet and we use the date formatting feature inside libreoffice in order to obtain ISO compliance. Dates are displayed correctly with ISO format inside the sheet but are not import by CSVImport.
