### ISSUE TITLE
Invalid settings: basic-settings: Array

### ISSUE THREAD

**Issue by andrisi** [omeka-s-modules/CSVImport#197]
Omeka: 3.1.2
CSV Import: 2.3.0

Import fails with two red error bubbles with no further explnations: "Invalid settings." + "basic-settings: Array". Am I doing something wrong? Why we don't have more explanations?

**Comment by zerocrates** [comment]
It looks like the code that should be printing a more helpful error message there isn't working properly, which is why you're getting "Array" printed there.

Does this happen every time you try to import?

**Comment by andrisi** [comment]
yes (with the same file)

**Comment by zerocrates** [comment]
I'm going to guess that you have nothing selected for "Sites" under the Basic Settings tab?

That's a bug that was introduced into the newest version of CSV Import: it's supposed to allow that field to be blank but it doesn't. If that's the case, we should have a fix in for your problem.

I've also fixed the problem where the error message just says "Array" instead of something more useful.

**Comment by andrisi** [comment]
Good guess, there was no "Sites" selection. Will retry a bit later.

**Comment by zerocrates** [comment]
OK, thanks for that info. I'll push an updated version of the module that contains those fixes.

**Comment by andrisi** [comment]
thanks @zerocrates
