### ISSUE TITLE
Testing/docs: resource-identifier-property branch

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/CSVImport#216]
The branch resource-identifier-property has an improvement to the way that mapping works when you use the "Omeka resource" data type from the options menu for a column (so, the option used to make linkages between resources).

In prior versions, this choice only works when the content of the CSV cell you're mapping is the Omeka S ID for the resource you want to link to, so you need to know the ID for what you're linking to, meaning you have to do your import in multiple steps and pull out the IDs of previous created resources so you can put them in the sheet to create the linkages later.

The resource-identifier-property branch removes that limitation, and it adds a new option named "Resource identifier property" in the column options sidebar. The choice here only has an effect when the "Data type" is set to "Omeka resource", and it lets you choose what kind of data is used to look up the resource to link to, allowing you to use any property, along with the old default of the ID.

The most important difference this creates, is that you no longer need to do the process of going in and out of the system and matching up IDs for the resources that got created to your sheet: you can just do an import where each row includes an external identifier, map that as dcterms:identifier, and then when you go to do a "resource" mapping for one column, you can choose dcterms:identifier as the "Resource identifier property" and the importer can make the link. This also works with items that are already in the system, as long as they have some suitable metadata value to match against.

This should work across the "normal" import types (items,sets,media,resources), and for regular "create" imports as well as the ones that do updates.

The feature here makes a "two-step" process much simpler (step one, create all the items, step two, make the links in an update import) because it's no longer necessary to look up IDs between the steps. A "one-step" import that makes links between things that are added in the same import is also newly possible here, but care needs to be taken as to the order the resources appear in the sheet and the batch size, so they're created before they're referenced as a link by another item.

**Comment by allanaaa** [comment]
The Undo column no longer works - you can't check any boxes to undo past imports.

**Comment by allanaaa** [comment]
On first glance, this appears to work. I did an Append import, because I had multiple rows of information to add per item. I started by creating a bunch of "Musical group" items at the top of the CSV and then created a bunch of "Musician" items that were linked to their respective groups, appending extra row info as needed to each musician. The resource linking worked fine. (The appending itself seems to have failed to be able to look up the existing item created in the previous row.) 

Where I had failed to create one musical group before trying to link to it, there was an error, but the process carried on. 

There are a few errors I can't understand. The first musician in the list had all three of his links come up with errors, although subsequent musicians linking to the same groups worked fine. 

I've just moved him to the end for a second import attempt and it seems to have worked fine. I took the batch-rows number down to 1 for this one.

I think maybe CSV Import works a little too quickly to make links to things that are still being created from the CSV, if you're looking up a new item by dcterms:title for example. You might want to introduce some intentional latency for this purpose.

**Comment by zerocrates** [comment]
There isn't (or shouldn't be) a _timing_ issue, but there can be an order issue, in combination with the batch size: the linkage won't work if the records you're trying to link to were created in the same batch.

**Comment by zerocrates** [comment]
I haven't touched Undo or stuff related to it so I doubt that's related.

**Comment by allanaaa** [comment]
> I haven't touched Undo or stuff related to it so I doubt that's related.

I mean, I wouldn't merge this until it's fixed!

**Comment by zerocrates** [comment]
What are you seeing happen with the Undo stuff? A screenshot, if it's visible in a screenshot, would be good.

**Comment by allanaaa** [comment]
It's just that the boxes are unclickable. 

<img width="936" alt="Screenshot 2024-01-20 at 13 22 23" src="https://github.com/omeka-s-modules/CSVImport/assets/28012148/8c11ffb9-e24f-45c9-a9de-6a8965535465">

Disabled=disabled???

<img width="647" alt="Screenshot 2024-01-20 at 13 23 22" src="https://github.com/omeka-s-modules/CSVImport/assets/28012148/379a731a-38b9-4d3b-a0dc-bb2555715fcd">

**Comment by zerocrates** [comment]
You can't (and haven't previously been able to) undo appends/updates/etc. Only "create" jobs, since an undo just deletes the created resources.

**Comment by allanaaa** [comment]
Oh I see, it's just that I haven't done a strict Create job in a long time. There are like two undo-able jobs on the whole page. My bad!
