### ISSUE TITLE
Undo doesn't fully complete

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/CSVImport#52]
Ran an undo of an import (279 data only items) and it left 93 remaining items. The system says that the undo is complete, and only one of the remaining items had been edited since import.

**Comment by patrickmj** [comment]
Curiouser and curiouser! Import and undo on the file you sent deleted everything imported. It didn't take long enough for me to suspect some variety of timeout on the server, but maybe that's it. 

I used the default mappings, which also look like they have some oddities in them:

* lots of empty header columns after 'Ship'
* bio:birth; dc:date being combined to one column because of ; instead of ,
* the above gets automapped to Title by CSVImport, a problem in CSVImport
* "relationship:SpouseOf,ParentOf,ChildOf,SiblingOf" combined to one column because of the ""s

Dunno if those observations have anything to do with the import/undo issue, but worth noting just in case.

**Comment by sharonmleon** [comment]
I did do the mapping manually and I skipped a lot of the columns--most of the ones that caused difficulty. But, the server time out didn't really occur to me. Since it's on shared hosting, that might really be it.

**Comment by patrickmj** [comment]
Whether it really is a server timeout (which I think merits investigation), might be that we should allow multiple tries at undoing. Currently, if there's a problem with the undo, there's not a way to do the undo a second time.

**Comment by sharonmleon** [comment]
Ahh... Good point.
