### ISSUE TITLE
reloading mapping page produces emptiness

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CSVImport#62]
Should either warn, or at least provide a start over button

**Comment by zerocrates** [comment]
A warning is standard browser behavior as this page is from a POST (I briefly had troubles where it was letting me reload but a Chrome upgrade seems to have resolved those).

The more likely underlying problem here (and for another of your issues) is the replaceState call that's issued when you switch between tabs (it's part of the admin UI's global.js). replaceState basically doesn't work if you're in a page that comes from a POST: its spec-defined behavior is to make the browser think that the current page is a GET, so refreshes are allowed without warning.

The only way I can think of to fix this is to not issue the replaceState call (so, don't put the fragment into the URL bar when switching tabs), since you can't use the fragment here anyway (well, only if you crammed it into the import form's `action` and nobody's going to do that).

I'm not sure how I'd go about doing that just here though (this is one of the only places where there's a form with tabs that comes from a POST, in fact very few Omeka pages come from POSTs by design, most POSTs issue immediate redirects). Putting a class somewhere that we check before calling replaceState seems like the only workable option.
